# Generated by Django 5.0 on 2023-12-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('UserCount', models.IntegerField(default=1)),
                ('JobCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=128)),
                ('MName', models.CharField(max_length=128)),
                ('LName', models.CharField(max_length=128)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.IntegerField()),
                ('IsNegotiable', models.BooleanField(default=False)),
                ('Address', models.CharField(blank=True, max_length=2048, null=True)),
                ('Lat', models.FloatField(blank=True, null=True)),
                ('Lon', models.FloatField(blank=True, null=True)),
                ('AllowsRemote', models.BooleanField(default=False)),
                ('Org', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org')),
            ],
        ),
        migrations.CreateModel(
            name='JobTagRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tags')),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='ManagedBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTagRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProficiencyLevel', models.IntegerField(default=0)),
                ('Years', models.IntegerField(default=0)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tags')),
            ],
        ),
    ]
