# Generated by Django 5.0 on 2023-12-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtagrelations',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tags', to='api.job'),
        ),
        migrations.AlterField(
            model_name='jobtagrelations',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='api.tags'),
        ),
    ]
