# Generated by Django 5.0 on 2023-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
