# Generated by Django 5.0 on 2023-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Proposal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ApplicationCount',
            field=models.IntegerField(default=0),
        ),
    ]
