# Generated by Django 5.0 on 2023-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_applications_proposal_job_applicationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.CharField(default='JOB', max_length=8192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Name',
            field=models.CharField(default='JOOB', max_length=128),
            preserve_default=False,
        ),
    ]
