# Generated by Django 5.0 on 2023-12-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_description_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org'),
        ),
    ]
