# Generated by Django 5.0 on 2023-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_applications_chosen_job_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Chosen',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
