# Generated by Django 5.0 on 2023-12-13 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_applications_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtagrelations',
            name='ProficiencyLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtagrelations',
            name='Years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='org',
            name='Address',
            field=models.CharField(default='Hell', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='org',
            name='Joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('File', models.FileField(upload_to='')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
    ]
