# Generated by Django 5.0 on 2023-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobtagrelations_proficiencylevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='Description',
            field=models.CharField(default='AAA', max_length=8192),
            preserve_default=False,
        ),
    ]
