# Generated by Django 5.0 on 2023-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_initalized_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
